// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzP0_b4JdszntS9dEjH4Yjev2NZEuXmBc',
    appId: '1:490816251747:web:43927e02bb50afa4f99556',
    messagingSenderId: '490816251747',
    projectId: 'moneta-knife-hit',
    authDomain: 'moneta-knife-hit.firebaseapp.com',
    storageBucket: 'moneta-knife-hit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwAj405vV-vx2evtoWRPR8g9Ac0LKOnk',
    appId: '1:490816251747:android:07289a10f93f4afcf99556',
    messagingSenderId: '490816251747',
    projectId: 'moneta-knife-hit',
    storageBucket: 'moneta-knife-hit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANpw-nnhvLPzgG_t9jK_ww1-ZxA9n7d3E',
    appId: '1:490816251747:ios:43f4c0f9b697ef29f99556',
    messagingSenderId: '490816251747',
    projectId: 'moneta-knife-hit',
    storageBucket: 'moneta-knife-hit.firebasestorage.app',
    iosBundleId: 'com.moneta.knifehit.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANpw-nnhvLPzgG_t9jK_ww1-ZxA9n7d3E',
    appId: '1:490816251747:ios:b70c13a3143292cff99556',
    messagingSenderId: '490816251747',
    projectId: 'moneta-knife-hit',
    storageBucket: 'moneta-knife-hit.firebasestorage.app',
    iosBundleId: 'com.example.knifeHitGame',
  );
}
